"""Add Like functionality to Trips

Revision ID: 9cdb1366f0c1
Revises: dbf65982926b
Create Date: 2017-10-10 08:32:09.553219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cdb1366f0c1'
down_revision = 'dbf65982926b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('number_of_likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip', 'number_of_likes')
    # ### end Alembic commands ###
